-- DROP SCHEMA `ejscdbsor` ;
-- CREATE SCHEMA `ejscdbsor` ;
use ejscdbstg;

CREATE TABLE PROCESS_ETL
(
	PROCESS_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY
)
;

CREATE TABLE CHANNELS_TRA
    ( 
     ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
     CHANNEL_ID integer  NOT NULL , 
     CHANNEL_DESC VARCHAR (20)  NOT NULL , 
     CHANNEL_CLASS VARCHAR (20)  NOT NULL , 
     CHANNEL_CLASS_ID integer  NOT NULL, 
     PROCESS_ID integer NOT NULL
    )
;


CREATE TABLE COUNTRIES_TRA 
    ( 
	 ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
     COUNTRY_ID integer  NOT NULL , 
     COUNTRY_NAME VARCHAR (40)  NOT NULL , 
     COUNTRY_REGION VARCHAR (20)  NOT NULL , 
     COUNTRY_REGION_ID integer  NOT NULL,
     PROCESS_ID integer NOT NULL
    ) 
;


CREATE TABLE CUSTOMERS_TRA 
    ( 
     ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
     CUST_ID integer  NOT NULL , 
     CUST_FIRST_NAME VARCHAR (20)  NOT NULL , 
     CUST_LAST_NAME VARCHAR (40)  NOT NULL , 
     CUST_NOM_COM VARCHAR (200) NOT NULL ,
     CUST_GENDER CHAR (1)  NOT NULL ,
     CUST_GEN VARCHAR (20) NOT NULL ,
     CUST_YEAR_OF_BIRTH integer (4)  NOT NULL , 
     CUST_MARITAL_STATUS VARCHAR (20) , 
     CUST_STREET_ADDRESS VARCHAR (40)  NOT NULL , 
     CUST_POSTAL_CODE VARCHAR (10)  NOT NULL , 
     CUST_CITY VARCHAR (30)  NOT NULL , 
     CUST_STATE_PROVINCE VARCHAR (40)  NOT NULL , 
     COUNTRY_ID integer  NOT NULL , 
     CUST_MAIN_PHONE_NUMBER VARCHAR (25)  NOT NULL , 
     CUST_INCOME_LEVEL VARCHAR (30) , 
     CUST_CREDIT_LIMIT integer , 
     CUST_EMAIL VARCHAR (30),
     PROCESS_ID integer NOT NULL
    )
;


CREATE TABLE PRODUCTS_TRA 
    ( 
     ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
     PROD_ID integer (6)  NOT NULL , 
     PROD_NAME VARCHAR (50)  NOT NULL , 
     PROD_DESC VARCHAR (4000)  NOT NULL , 
     PROD_CATEGORY VARCHAR (50)  NOT NULL , 
     PROD_CATEGORY_ID integer  NOT NULL , 
     PROD_CATEGORY_DESC VARCHAR (2000)  NOT NULL , 
     PROD_WEIGHT_CLASS integer (3)  NOT NULL , 
     SUPPLIER_ID integer (6)  NOT NULL , 
     PROD_STATUS VARCHAR (20)  NOT NULL , 
     PROD_LIST_PRICE decimal (8,2)  NOT NULL , 
     PROD_MIN_PRICE decimal (8,2)  NOT NULL ,
     PROCESS_ID integer NOT NULL
    )
;

CREATE TABLE PROMOTIONS_TRA 
    ( 
	 ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
     PROMO_ID integer (6)  NOT NULL , 
     PROMO_NAME VARCHAR (30)  NOT NULL , 
     PROMO_COST decimal (10,2)  NOT NULL , 
     PROMO_BEGIN_DATE DATE  NOT NULL , 
     PROMO_END_DATE DATE  NOT NULL,
     PROCESS_ID integer NOT NULL
    )
;


CREATE TABLE SALES_TRA 
    ( 
     ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
     PROD_ID integer (6)  NOT NULL , 
     CUST_ID integer  NOT NULL , 
     TIME_ID DATE  NOT NULL , 
     CHANNEL_ID integer  NOT NULL , 
     PROMO_ID integer (6)  NOT NULL , 
     QUANTITY_SOLD decimal (10,2)  NOT NULL , 
     AMOUNT_SOLD decimal (10,2)  NOT NULL ,
     PROCESS_ID integer NOT NULL
    ) 
;

CREATE TABLE TIMES_TRA 
    ( 
     TIME_ID integer  NOT NULL PRIMARY KEY, 
     DAY_NAME VARCHAR (9)  NOT NULL , 
     DAY_NUMBER_IN_WEEK integer (1)  NOT NULL , 
     DAY_NUMBER_IN_MONTH integer (2)  NOT NULL , 
     CALENDAR_WEEK_NUMBER integer (2)  NOT NULL , 
     CALENDAR_MONTH_NUMBER integer (2)  NOT NULL , 
     CALENDAR_MONTH_DESC VARCHAR (8)  NOT NULL , 
     END_OF_CAL_MONTH DATE  NOT NULL , 
     CALENDAR_QUARTER_DESC CHAR (7)  NOT NULL , 
     CALENDAR_YEAR integer (4)  NOT NULL ,
     PROCESS_ID integer NOT NULL
    ) 
;

