use ejscdbstg; 


CREATE TABLE CHANNELS_EXT 
    ( 
     CHANNEL_ID CHARACTER  NOT NULL , 
     CHANNEL_DESC CHARACTER(20)  NOT NULL , 
     CHANNEL_CLASS CHARACTER (20)  NOT NULL , 
     CHANNEL_CLASS_ID CHARACTER (6) NOT NULL 
    )
;

ALTER TABLE CHANNELS_EXT 
    ADD CONSTRAINT CHANNELS_PK PRIMARY KEY ( CHANNEL_ID ) ;


CREATE TABLE COUNTRIES_EXT
    ( 
     COUNTRY_ID CHARACTER (5) NOT NULL , 
     COUNTRY_NAME CHARACTER (40)  NOT NULL , 
     COUNTRY_REGION CHARACTER (20)  NOT NULL , 
     COUNTRY_REGION_ID CHARACTER (6) NOT NULL 
    ) 
;


ALTER TABLE COUNTRIES_EXT 
    ADD CONSTRAINT COUNTRIES_PK PRIMARY KEY ( COUNTRY_ID ) ;


CREATE TABLE CUSTOMERS_EXT 
    ( 
     CUST_ID CHARACTER (6) NOT NULL , 
     CUST_FIRST_NAME CHARACTER (20)  NOT NULL , 
     CUST_LAST_NAME CHARACTER (40)  NOT NULL , 
     CUST_GENDER CHARACTER (1)  NOT NULL , 
     CUST_YEAR_OF_BIRTH CHARACTER (4)  NOT NULL , 
     CUST_MARITAL_STATUS CHARACTER (20) , 
     CUST_STREET_ADDRESS CHARACTER (40)  NOT NULL , 
     CUST_POSTAL_CODE CHARACTER (10)  NOT NULL , 
     CUST_CITY CHARACTER (30)  NOT NULL , 
     CUST_STATE_PROVINCE CHARACTER (40)  NOT NULL , 
     COUNTRY_ID CHARACTER (6)  NOT NULL , 
     CUST_MAIN_PHONE_NUMBER CHARACTER (25)  NOT NULL , 
     CUST_INCOME_LEVEL CHARACTER (30) , 
     CUST_CREDIT_LIMIT CHARACTER (6) , 
     CUST_EMAIL CHARACTER (30)
    )
;


ALTER TABLE CUSTOMERS_EXT 
    ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY ( CUST_ID ) ;


CREATE TABLE PRODUCTS_EXT 
    ( 
     PROD_ID CHARACTER (6)  NOT NULL , 
     PROD_NAME CHARACTER (50)  NOT NULL , 
     PROD_DESC TEXT (4000)  NOT NULL , 
     PROD_CATEGORY CHARACTER (50)  NOT NULL , 
     PROD_CATEGORY_ID CHARACTER (6) NOT NULL , 
     PROD_CATEGORY_DESC TEXT (2000)  NOT NULL , 
     PROD_WEIGHT_CLASS CHARACTER (3)  NOT NULL , 
     SUPPLIER_ID CHARACTER (6)  NOT NULL , 
     PROD_STATUS CHARACTER (20)  NOT NULL , 
     PROD_LIST_PRICE CHARACTER (11)  NOT NULL , 
     PROD_MIN_PRICE CHARACTER (11)  NOT NULL 
    )
;



ALTER TABLE PRODUCTS_EXT 
    ADD CONSTRAINT PRODUCTS_PK PRIMARY KEY ( PROD_ID ) ;


CREATE TABLE PROMOTIONS_EXT 
    ( 
     PROMO_ID CHARACTER (6)  NOT NULL , 
     PROMO_NAME CHARACTER (30)  NOT NULL , 
     PROMO_COST CHARACTER (13)  NOT NULL , 
     PROMO_BEGIN_DATE CHARACTER (9) NOT NULL , 
     PROMO_END_DATE CHARACTER (9) NOT NULL 
    )
;


ALTER TABLE PROMOTIONS_EXT 
    ADD CONSTRAINT PROMO_PK PRIMARY KEY ( PROMO_ID )  ;


CREATE TABLE SALES_EXT 
    ( 
     PROD_ID CHARACTER (6)  NOT NULL , 
     CUST_ID CHARACTER (6) NOT NULL , 
     TIME_ID CHARACTER (9) NOT NULL , 
     CHANNEL_ID CHARACTER  NOT NULL , 
     PROMO_ID CHARACTER (6)  NOT NULL , 
     QUANTITY_SOLD CHARACTER (13)  NOT NULL , 
     AMOUNT_SOLD CHARACTER (13)  NOT NULL 
    ) 
;


CREATE TABLE TIMES_EXT 
    ( 
     TIME_ID CHARACTER (9) NOT NULL , 
     DAY_NAME CHARACTER (9)  NOT NULL , 
     DAY_NUMBER_IN_WEEK CHARACTER (1)  NOT NULL , 
     DAY_NUMBER_IN_MONTH CHARACTER (2)  NOT NULL , 
     CALENDAR_WEEK_NUMBER CHARACTER (2)  NOT NULL , 
     CALENDAR_MONTH_NUMBER CHARACTER (2)  NOT NULL , 
     CALENDAR_MONTH_DESC CHARACTER (8)  NOT NULL , 
     END_OF_CAL_MONTH CHARACTER (9) NOT NULL , 
     CALENDAR_MONTH_NAME CHARACTER (9) NULL , 
     CALENDAR_QUARTER_DESC CHARACTER (7)  NOT NULL , 
     CALENDAR_YEAR CHARACTER (4)  NOT NULL 
    ) 
;



ALTER TABLE TIMES_EXT 
    ADD CONSTRAINT TIMES_PK PRIMARY KEY ( TIME_ID )  ;


